ALTER TABLE comentari ADD CONSTRAINT FK_COMENTARI_RESPONSABLEOBJECTIU FOREIGN KEY (id_responsable_objectiu) REFERENCES responsable(id_responsable) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE subscripcio RENAME COLUMN estat TO id_estat;
ALTER TABLE subscripcio ADD CONSTRAINT FK_SUBSCRIPCIO_ESTAT FOREIGN KEY (id_estat) REFERENCES estat(id_estat) ON DELETE NO ACTION ON UPDATE NO ACTION;
